1- UTM_SETTINGS =(By.ID, "enableUtmSettings")
2- CONTENT =(BY.CLASS_NAME, "attributeListWrapper")
3- SEARCH =(BY.ID, "search-value")
4- TEST =(BY.ID, "Test")
5- STATISTICS =(BY.LINKTEXT, "/journey-builder/129069/overall-statistics")
6- CROSS_ICON =(BY.XPATH, "//*[@id="delete"]")
7- REMOVE/CHANGE =(BY.CLASS_NAME, "elementOption elementOption animationHalf")
8- TOASTER =(BY.CLASS_NAME, "in-toasts-wrapper m-4 qa-toasts")
9- CREATE =(BY.ID, "create-architect")